title             : Kustom Imports
description       : Spice up your Android device with our collection of Kustom imports
repository        : tbr-development/Kustom  
permalink         : pretty
remote_theme      : just-the-docs/just-the-docs 
color_scheme      : "dark" 
search_enabled    : true
