title: Kustom
description: Imports for use with Kustom
url: https://tbr-development.github.io/Kustom

theme: just-the-docs
color_scheme: dark

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub" 
gh_edit_repository: "https://github.com/tbr-development/Kustom" 
gh_edit_branch: "main" 
gh_edit_view_mode: "tree"
gh_edit_source: "docs"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

back_to_top: true
back_to_top_text: "Back to top" 
  
footer_content: "Copyright &copy; 2023 TBR Development. Distributed by an <a href=\"https://github.com/tbr-development/Kustom/tree/main/LICENSE\">MIT license</a>."
