title: Kustom
description: Imports for use with Kustom
theme: just-the-docs
url: https://tbr-development.github.io/Kustom

gh_edit_link: true # show or hide edit this page link 
gh_edit_link_text: "Edit this page on GitHub" 
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo 
gh_edit_branch: "main" 
gh_edit_view_mode: "tree"
gh_edit_source: "docs"


color_scheme: dark
